version: '3.8'

services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - SUPERADMIN_ID=${SUPERADMIN_ID}
      - DATABASE_URL=sqlite:///data/birthday_bot.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped